In [1]:
import spacy

In [2]:
nlp = spacy.load("en_core_web_sm")

In [9]:
analytics_document = nlp("He is reading books with other students while eating meal.")

for token in analytics_document:
    print(token.text, token.lemma_, token.is_stop )

# lemma : 단어의 기본형
# is_stop : 

He he True
is be True
reading read False
books book False
with with True
other other True
students student False
while while True
eating eat False
meal meal False
. . False


In [8]:
txt = "This is the first sentence. However, all the other Ph.D. students are working on , say , second sentece."

txt_analytics = nlp(txt)
for sentence in txt_analytics.sents: # .sents = 단어 단위가 아니라 문장단위.
    print(sentence)

This is the first sentence.
However, all the other Ph.D. students are working on , say , second sentece.


In [10]:
!pip install editdistance

Using legacy 'setup.py install' for editdistance, since package 'wheel' is not installed.
    Running setup.py install for editdistance: started
    Running setup.py install for editdistance: finished with status 'error'


    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\SONG\Desktop\SEOUL_AI\20210724\venv_20210724\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\SONG\\AppData\\Local\\Temp\\pip-install-dcecddb7\\editdistance_1d2ab44a0c3545b9ab56f70a4ab94461\\setup.py'"'"'; __file__='"'"'C:\\Users\\SONG\\AppData\\Local\\Temp\\pip-install-dcecddb7\\editdistance_1d2ab44a0c3545b9ab56f70a4ab94461\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\SONG\AppData\Local\Temp\pip-record-jyjxx2i6\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\SONG\Desktop\SEOUL_AI\20210724\venv_20210724\include\site\python3.9\editdistance'
         cwd: C:\Users\SONG

In [11]:
def nGrams(doc_string_or_list, n, docIsAlreadTokenized):
    doc = doc_string_or_list
    if not docIsAlreadTokenized:
        doc = [token.text for token in nlp(doc_string_or_list)]
    doc = " ".join(doc).lower().split(' ')
    grams = [doc[i:i+n] for i in range(len(doc)-n+1)]
    return grams

In [16]:
doc = "How old are you today OR can you tell me somthing about you"
n = 4

# n = 1 : 유니그램(unigram)
# n = 2 : 바이그램(bigram)
# n = 3 : 트라이그램 (trigram)
# n >= 4 : n-gram

grams = nGrams(doc, n, False)

In [17]:
grams

[['how', 'old', 'are', 'you'],
 ['old', 'are', 'you', 'today'],
 ['are', 'you', 'today', 'or'],
 ['you', 'today', 'or', 'can'],
 ['today', 'or', 'can', 'you'],
 ['or', 'can', 'you', 'tell'],
 ['can', 'you', 'tell', 'me'],
 ['you', 'tell', 'me', 'somthing'],
 ['tell', 'me', 'somthing', 'about'],
 ['me', 'somthing', 'about', 'you']]

In [18]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [23]:
L = list(nlp.vocab.strings)
numWords = len(L)
print(numWords)

83814


In [25]:
import numpy as np 
W2I = dict(zip(L, np.arange(numWords)))
I2W = dict(zip(np.arange(numWords), L))

In [31]:
np.arange(numWords)

array([    0,     1,     2, ..., 83811, 83812, 83813])

In [32]:
W2I

{'\t': 0,
 '\n': 1,
 ' ': 2,
 '  ': 3,
 '!': 4,
 '!!': 5,
 '!!!': 6,
 '!!!!': 7,
 '!!!!!!!!!!!!!!!!': 8,
 '!!!!.': 9,
 '!!.': 10,
 '!!?': 11,
 '!!??': 12,
 '!*': 13,
 '!.': 14,
 '!?': 15,
 '!??': 16,
 '"': 17,
 '""': 18,
 '#': 19,
 "##'s": 20,
 "##'x": 21,
 "#'s": 22,
 '#15': 23,
 '#^%': 24,
 '#dd': 25,
 '$': 26,
 '$19': 27,
 '$Whose': 28,
 '$Xxxxx': 29,
 '$whose': 30,
 '$xxxx': 31,
 '%': 32,
 '%-3': 33,
 '%ach': 34,
 '%ah': 35,
 '%eh': 36,
 '%er': 37,
 '%ha': 38,
 '%hm': 39,
 '%huh': 40,
 '%mm': 41,
 '%oof': 42,
 '%pw': 43,
 '%uh': 44,
 '%um': 45,
 '%xx': 46,
 '%xxx': 47,
 '&': 48,
 '&#': 49,
 '&G.': 50,
 '&L.': 51,
 '&Ls': 52,
 '&M.': 53,
 '&P.': 54,
 '&SA': 55,
 '&T.': 56,
 '&ex': 57,
 '&in': 58,
 '&ls': 59,
 '&of': 60,
 '&on': 61,
 '&sa': 62,
 '&the': 63,
 '&to': 64,
 '&uh': 65,
 '&von': 66,
 '&xx': 67,
 '&xxx': 68,
 "'": 69,
 "''": 70,
 "''It": 71,
 "''Xx": 72,
 "''it": 73,
 "''xx": 74,
 "'-(": 75,
 "'-)": 76,
 "'03": 77,
 "'07": 78,
 "'20s": 79,
 "'30s": 80,
 "'40s": 81,
 "'45": 

In [33]:
I2W

{0: '\t',
 1: '\n',
 2: ' ',
 3: '  ',
 4: '!',
 5: '!!',
 6: '!!!',
 7: '!!!!',
 8: '!!!!!!!!!!!!!!!!',
 9: '!!!!.',
 10: '!!.',
 11: '!!?',
 12: '!!??',
 13: '!*',
 14: '!.',
 15: '!?',
 16: '!??',
 17: '"',
 18: '""',
 19: '#',
 20: "##'s",
 21: "##'x",
 22: "#'s",
 23: '#15',
 24: '#^%',
 25: '#dd',
 26: '$',
 27: '$19',
 28: '$Whose',
 29: '$Xxxxx',
 30: '$whose',
 31: '$xxxx',
 32: '%',
 33: '%-3',
 34: '%ach',
 35: '%ah',
 36: '%eh',
 37: '%er',
 38: '%ha',
 39: '%hm',
 40: '%huh',
 41: '%mm',
 42: '%oof',
 43: '%pw',
 44: '%uh',
 45: '%um',
 46: '%xx',
 47: '%xxx',
 48: '&',
 49: '&#',
 50: '&G.',
 51: '&L.',
 52: '&Ls',
 53: '&M.',
 54: '&P.',
 55: '&SA',
 56: '&T.',
 57: '&ex',
 58: '&in',
 59: '&ls',
 60: '&of',
 61: '&on',
 62: '&sa',
 63: '&the',
 64: '&to',
 65: '&uh',
 66: '&von',
 67: '&xx',
 68: '&xxx',
 69: "'",
 70: "''",
 71: "''It",
 72: "''Xx",
 73: "''it",
 74: "''xx",
 75: "'-(",
 76: "'-)",
 77: "'03",
 78: "'07",
 79: "'20s",
 80: "'30s",
 81: "'40s",
 82: "'4

In [35]:
W2I['game']

49410

In [36]:
I2W[23456]

'Printed'

In [37]:
def oneHotVector(word, W2I, numWords):
    v = np.zeros(numWords)
    v[W2I[word]] = 1
    return v

In [39]:
v = oneHotVector("game", W2I, numWords)
v, v.shape, v[49410], v[W2I["game"]]

(array([0., 0., 0., ..., 0., 0., 0.]), (83814,), 1.0, 1.0)

In [67]:
doc = "How are you today. I know most of the time how you feel. ."

# 이 doc를 토큰화한 다음 리스트로 만들어보시오.

tokens = [token.text for token in nlp(doc)]
numWords = len(tokens)
print(tokens, "\n", numWords, "\n", type(tokens))

W2I = dict(zip(tokens, np.arange(numWords)))
I2W = dict(zip(np.arange(numWords), tokens))

print(W2I["feel"])
print(I2W[13])


['How', 'are', 'you', 'today', '.', 'I', 'know', 'most', 'of', 'the', 'time', 'how', 'you', 'feel', '.', '.'] 
 16 
 <class 'list'>
13
feel


In [68]:
v = np.zeros(numWords)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
for token in tokens:
    v += oneHotVector(token, W2I, numWords) # 빈도수. 해당 인덱스의 개수를 더하는

In [70]:
v

array([1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 2., 1., 0., 3.])